spring:
  rabbitmq:
    host: 192.168.177.158
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    publisher-confirms: true #如果对异步消息需要回调必须设置为true





#  mq.config.exchange=log.direct
#
#  mq.config.queue.info=log.info
#
#  mq.config.queue.info.routing.key=log.info.routing.key
#
#  mq.config.queue.error=log.error
#
#  mq.config.queue.error.routing.key=log.error.routing.key

